#!/bin/bash

#================================================================================
#Nome file= file_gestione_processi.sh
#Descrizione esercizio= Gestione dei processi,cicli,errori e contatori in Bash
#================================================================================

#1)Prima cosa definisco delle variabili:le metto in maiuscolo proprio perchè devono essere costanti.

NUM_PROCESSI=5

#è ilnumero di volte che il ciclo for deve girare, per il momento ne lascio 5 poi vedrò se aumentare

#Ciclo for
for((i=1; i<=NUM_PROCESSI; i++))do
        echo "Processo $i  in esecuzione..."

done

# Dai i permessi di esecuzione
#chmod +x gestione_processi.sh

# Esegui lo script
#./file_gestione_errori_completo.sh

# Come Output avrò:
#Processo 1  in esecuzione...
#Processo 2  in esecuzione...
#Processo 3  in esecuzione...
#Processo 4  in esecuzione...
#Processo 5  in esecuzione...


