Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox"

  config.vm.define "node1" do |node|
    node.vm.hostname = "node1"
    node.vm.network "private_network", ip: "192.168.56.10"
    node.vm.provision "shell", path: "file_capra_cavoli.sh"
  end
  config.vm.define "node2" do |node|
    node.vm.hostname = "node2"
    node.vm.network "private_network", ip: "192.168.56.11"
    node.vm.provision "shell", path: "file_capra_cavoli.sh"
  end
end
