#Attraverso questo script fornisco a Vagrant le istruzioni esatte per costruire 
#e configurare la macchina virtuale che mi serve per l'esercizio.

#Inizio aprendo il file di configurazione e dico a vagrant di usare la seconda versione della sua sintassi(standard attuale)
#Poi inizio la configurazione decidendo come sistema operativo per le macchina virtuale dell'esercizio Ubuntu 20.04 LTS (Focal Fossa) a 64 bit.
#Assegnando "webserver" come nome host (hostname) all'interno del sistema operativo guest della macchina virtuale. 

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "webserver"


#Imposto una regola di port forwarding (inoltro delle porte).
#Faccio sì che tutto il traffico web indirizzato alla porta 8080 del mio computer fisico (il Mac) 
#venga automaticamente reindirizzato alla porta 80 della macchina virtuale
  config.vm.network "forwarded_port", guest: 80, host: 8080

#Configuro una rete privata tra il mio computer fisico e la macchina virtuale,
#assegnando a quest'ultima l'indirizzo IP statico 192.168.56.20,
#per far comunicare direttamente con la VM tramite questo indirizzo IP locale.
  config.vm.network "private_network", ip: "192.168.56.20"

#Ora faccio una configurazione solo per il virtualbox, il provider che ho scelto per
#eseguire la macchina virtuale(dove viene creata la vm). 

#Scelgo nome memoria ram e numero di cpu(1 core del processore).

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "webserver"
    vb.memory = "512"
    vb.cpus   = 1
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
#NB dato che ho avuto dei problemi con  virtualstudiocode che non riusciva a gestire il dns della VM ho inserito:
#vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"] che fa usare alla VM di usare il DNS del MAC e vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
#che Dice a VirtualBox di fare da proxy per le richieste DNS.

  
#Provisioner:Con questa parte di script dico a Vagrant di utilizzare Ansible come "provisioner",
# ovvero lo strumento che si occuperà di installare il software e configurare il sistema operativo 
# dopo che la macchina virtuale è stata creata e avviata. 
#Per fare questo ansible usa un file di istruzioni o playbook che è presente in questo progetto con il nome
# di "provisioner_Ansible.yml".
# Imposto la modalità verbosa in modo che man mano che esso lavora, posso vedere cosa fa dal terminale.

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioner_Ansible.yml"
    ansible.verbose  = "v"
  end

end
