pipeline {
    agent { label 'docker' }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/gabriele-riccio/formazione_sou.git'
            }
        }

        stage('Test connessione Ansible') {
            steps {
                withCredentials([
                    sshUserPrivateKey(credentialsId: 'rocky9-ssh-key', keyFileVariable: 'SSH_KEY', usernameVariable: 'SSH_USER'),
                    file(credentialsId: 'ansible-vault-pass', variable: 'VAULT_PASS_FILE')
                ]) {
                    dir('esercizi_ansible/ansible-lab') {
                        sh '''
                            export ANSIBLE_VAULT_PASSWORD_FILE=$VAULT_PASS_FILE
                            ansible rocky9 -m ping \
                              --private-key=$SSH_KEY \
                              -u $SSH_USER
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Connessione Ansible riuscita dalla pipeline Jenkins!'
        }
        failure {
            echo 'Connessione fallita, controlla i log della console'
        }
    }
}
