# ==============================================================================
# Vagrantfile — Esercizio capra, cavolo e lupo (versione Docker multi-VM)
# ==============================================================================
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox"

  config.vm.define "vm1" do |node|
    node.vm.hostname = "vm1"
    node.vm.network "private_network", ip: "192.168.56.10"
    node.vm.provision "shell", path: "file_prov_container.sh"
  end

  config.vm.define "vm2" do |node|
    node.vm.hostname = "vm2"
    node.vm.network "private_network", ip: "192.168.56.11"
    node.vm.provision "shell", path: "file_prov_container.sh"
  end
end
